const TRANSLATION = {
	en: {
		global: {
			cookies: {
				title: "Cookies",
				description:
					"This website uses cookies to ensure you get the best experience. Information about language and theme preferences are stored in cookies. Also some analytics are gathered with cookies.",
				buttons: {
					accept: "Accept cookies",
					acceptNecessary: "Accept necessary only",
					decline: "Decline all cookies",
				},
			},
			cookiesPreferences: {
				title: "Cookies preferences",
				description:
					"Accept necessary cookies to enable language and theme switching. To participate in analytics, accept all cookies.",
				currentSelection: "Current selection",
			},
			contact: {
				btnTxt: "Contact me",
				dialog: {
					title: "Contact me",
					subtitle: "Get in contact through your preferred social channel!",
					closeBtn: "Close",
				},
			},
			footer: {
				updated: "updated lastly",
				favicon: "favicon by Freepik",
				vatId: "Finnish Business ID",
			},
			navbar: {
				shortcuts: ["Home", "About", "Skills", "Projects", "Experience"],
			},
			projectPanel: {
				flagShip: "FLAGSHIP",
				newProject: "NEW",
			},
			theme: {
				light: "Light",
				dark: "Dark",
				system: "System",
			},
		},
		index: {
			aboutme: {
				title: "ABOUT ME",
				subtitle: "Data Storyteller with a Developer’s Mindset",
			},
			experience: {
				title: "EXPERIENCE",
				header: "Quick summary of my most recent experiences",
				present: "Present",
				visitLinkedIn:
					"Please check my LinkedIn profile to view my full resume in greater detail!",
				linkedInBtn: "View my LinkedIn profile",
			},
			newproject: {
				title: "CONTACT",
				hero: {
					title: "Let's chat!",
					subtitle: "Got a project in mind? I'd love to talk about it.",
				},
			},
			projects: {
				title: "PROJECTS",
				header: "Things I've built so far",
				moreBtn: {
					btnText: "and more...",
				},
			},
			skills: {
				title: "SKILLS",
				headers: {
					skills: "Technologies and tools I am good with",
					learning: "Additionally I'm currently learning",
				},
				listBtn: {
					showMore: "SHOW MORE",
					showLess: "SHOW LESS",
				},
				imgCredits: "Logos generated by shields.io",
			},
			title: {
				header: {
					hello: "Hello, I'm",
					subtitle:
						"a data analyst pursuing a master’s in Informatics Engineering at BINUS and studying at Purwadhika. I turn complex data into actionable insights, combining tech skills and analytical thinking to drive real-world impact.",
				},
				messageBtn: {
					btnTxt: "Send me a message",
					dialog: {
						title: "Send me a message",
						subtitle: "You reach me best via Telegram.",
						closeBtn: "Close",
					},
				},
				video: {
					overlays: {
						responsive: "RESPONSIVE",
						modern: "MODERN",
					},
					credits: "video by u_vt453kmgmm from Pixabay",
				},
			},
		},
		projects: {
			header: {
				title: "Projects",
				subtitle: "Curated catalogue of my recent work.",
			},
			footer: {
				title:
					"Find even more projects and the source code for this portfolio website on my GitHub!",
				btnText: "Check my GitHub",
			},
			newProject: {
				new: "NEW",
				dialog: {
					title: "New project in mind?",
					subtitle: "Get in contact and let's discuss how to proceed.",
					closeBtn: "Close",
				},
			},
		},
		project: {
			header: {
				backToProjectsBtn: {
					btnText: "Back to list",
				},
				sourceCodeBtn: {
					btnText: "View source code on GitHub",
					private: "Source code is private",
				},
			},
			demoLink: {
				btnText: "Check the live project on web",
				explotrack: "Check the demo project on web",
				deployedOn: "Deployed on",
			},
			video: {
				notWorking: {
					title: "Video not working?",
					btnText: "Open the video in Dropbox",
				},
				smallScreen: {
					title: "You are viewing this video on a really small screen!",
					subtitle:
						"If possible, I'd suggest switching to landscape mode for a better view.",
				},
			},
			description: {
				title: "Description",
			},
			learnMore: {
				private: {
					header: "Unfortunately the source code is private.",
					subtitle:
						"I'll still be happy to demo the project and/or answer any questions you might have!",
					btnText: "Contact me fore more info",
				},
				public: {
					header: "Want to learn more about this project?",
					subtitle:
						"Check the source code and read the full documentation on GitHub!",
					btnText: "Check the GitHub repo",
				},
			},
			navbar: {
				title: "Check other projects as well!",
			},
		},
		notFound: {
			title: "404",
			subtitle:
				"This is not the page you are looking for. Please check the URL.",
			btnText: "Return home",
		},
	},
	id: {
		global: {
			cookies: {
				title: "Evästeet",
				description:
					"Tämä verkkosivu hyödyntää evästeitä parhaan käyttökokemuksen varmistamiseksi. Tieto kielivalinnasta ja teemasta tallennetaan evästeisiin. Evästeillä kerätään myös analytiikkaa.",
				buttons: {
					accept: "Hyväksy evästeet",
					acceptNecessary: "Hyväksy vain välttämättömät",
					decline: "Kiellä kaikki evästeet",
				},
			},
			cookiesPreferences: {
				title: "Evästeasetukset",
				currentSelection: "Nykyinen valinta",
				description:
					"Välttämättömät evästeet tarvitaan kielen ja teeman vaihtoon. Sivuston käytöstä kerätään analytiikkaa, mikäli hyväksyt kaikki evästeet.",
			},
			contact: {
				btnTxt: "Ota yhteyttä",
				dialog: {
					title: "Ota yhteyttä",
					subtitle: "Mikä kanava sopisi sinulle parhaiten?",
					closeBtn: "Sulje",
				},
			},
			footer: {
				updated: "päivitetty viimeksi",
				favicon: "faviconin suunnitellut Freepik",
				vatId: "Y-tunnus",
			},
			navbar: {
				shortcuts: ["Koti", "Lyhyesti", "Taidot", "Projektit", "Työkokemus"],
			},
			projectPanel: {
				flagShip: "LIPPULAIVA",
				newProject: "UUSI",
			},
			theme: {
				light: "Vaalea",
				dark: "Tumma",
				system: "Järjestelmä",
			},
		},
		index: {
			aboutme: {
				title: "LYHYESTI",
				subtitle: "Motivoitunut web-kehitykseen erikoistunut moniosaaja",
			},
			experience: {
				title: "PENGALAMAN KERJA",
				header: "PENGALAMAN KERJA",
				present: "Saat ini",
				visitLinkedIn:
					"CV lengkap dan detail saya tersedia di LinkedIn.",
				linkedInBtn: "Lihat profil LinkedIn saya",
			},
			newproject: {
				title: "HUBUNGI SAYA",
				hero: {
					title: "Mari berbicara!",
					subtitle:
						"Punya proyek dalam pikiran? Saya akan sangat senang membicarakannya bersama Anda.",
				},
			},
			projects: {
				title: "PROYEK-PROYEK",
				header: "Proyek saya selama ini",
				moreBtn: {
					btnText: "dan lainnya...",
				},
			},
			skills: {
				title: "Keahlian",
				headers: {
					skills: "Teknologi dan alat yang saya kuasai",
					learning: "Saat ini saya juga sedang belajar",
				},
				listBtn: {
					showMore: "Lihat selengkapnya",
					showLess: "Sembunyikan",
				},
				imgCredits: "Logo dihasilkan oleh shields.io",
			},
			title: {
				header: {
					hello: "Hi, saya",
					subtitle:
						"seorang analis data yang saat ini sedang menempuh pendidikan magister Teknik Informatika di Universitas BINUS dan mengasah keterampilan praktis di Purwadhika. Saya mengkhususkan diri dalam mengubah data yang kompleks menjadi wawasan yang dapat ditindaklanjuti, dengan menggabungkan keahlian teknis dan pemikiran analitis untuk menciptakan dampak nyata melalui data.",
				},
				messageBtn: {
					btnTxt: "Kirim saya pesan",
					dialog: {
						title: "Kirimkan saya pesan",
						subtitle: "Saya paling mudah dihubungi lewat Whatsapp.",
						closeBtn: "Tutup",
					},
				},
				video: {
					overlays: {
						responsive: "RESPONSIF",
						modern: "MODERN",
					},
					credits: "video dari Pixabay oleh pengguna u_vt453kmgmm",
				},
			},
		},
		projects: {
			header: {
				title: "Proyek",
				subtitle: "Kumpulan hasil karya terbaru saya.",
			},
			footer: {
				title:
					"Kamu bisa menemukan semua proyek saya dan kode sumber untuk situs portfolio ini di GitHub saya!",
				btnText: "Buka profil GitHub saya",
			},
			newProject: {
				new: "UUSI",
				dialog: {
					title: "Ada ide proyek yang ingin direalisasikan?",
					subtitle: "Hubungi saya dan mari kita diskusikan langkah selanjutnya.",
					closeBtn: "Tutup",
				},
			},
		},
		project: {
			header: {
				backToProjectsBtn: {
					btnText: "Kembali ke tampilan list",
				},
				sourceCodeBtn: {
					btnText: "Tampilkan kode sumber di GitHub",
					private: "Kode ini bersifat privat.",
				},
			},
			demoLink: {
				btnText: "Silakan lihat proyek yang sedang berjalan langsung di internet.",
				explotrack: "Silakan lihat demo proyek ini di internet",
				deployedOn: "Proyek ini diunggah melalui",
			},
			video: {
				notWorking: {
					title: "Video tidak berfungsi?",
					btnText: "Buka di dropbox",
				},
				smallScreen: {
					title: "Kamu sedang menonton video dari layar yang sangat kecil!",
					subtitle:
						"Jika memungkinkan, saya sarankan memutar perangkat ke posisi horizontal untuk mendapatkan pengalaman menonton yang lebih baik.",
				},
			},
			description: {
				title: "Deskripsi",
			},
			learnMore: {
				private: {
					header: "Projek ini bersifat privat.",
					subtitle:
						"Saya tetap dengan senang hati akan menjawab semua pertanyaan dan/atau menjelaskan lebih lanjut tentang proyek ini!",
					btnText: "Hubungi saya dan tanyakan lebih lanjut.",
				},
				public: {
					header: "Apakah kamu ingin tahu lebih banyak tentang proyek ini?",
					subtitle:
						"Lihat kode sumber dan baca dokumentasi lengkapnya di GitHub!",
					btnText: "Buka repositori di GitHub",
				},
			},
			navbar: {
				title: "Silakan lihat juga proyek-proyek saya yang lain!",
			},
		},
		notFound: {
			title: "404",
			subtitle: "Halaman seperti ini tidak ada! Pastikan alamatnya benar.",
			btnText: "Kembali ke beranda",
		},
	},
};

export default TRANSLATION;
